# Generated by Django 4.2.11 on 2024-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("duration", models.PositiveIntegerField()),
                (
                    "rating",
                    models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
                ),
                ("year_of_release", models.PositiveIntegerField()),
                ("studio", models.CharField(max_length=30)),
            ],
        ),
    ]
