# Generated by Django 4.2.11 on 2024-05-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="rating",
            field=models.DecimalField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                decimal_places=1,
                max_digits=3,
            ),
        ),
    ]
