# Generated by Django 4.2.11 on 2024-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviesapp", "0002_alter_show_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="rating",
            field=models.FloatField(
                choices=[
                    (0.5, 0.5),
                    (1.0, 1.0),
                    (1.5, 1.5),
                    (2.0, 2.0),
                    (2.5, 2.5),
                    (3.0, 3.0),
                    (3.5, 3.5),
                    (4.0, 4.0),
                    (4.5, 4.5),
                    (5.0, 5.0),
                ]
            ),
        ),
    ]
